# Generated by Django 4.2.6 on 2023-11-18 10:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format:Up to 10 digits allowed.', regex='^\\d{10,10}$')])),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('type_user', models.CharField(choices=[('student', 'student'), ('supervisor', 'supervisor')], default='student', max_length=20)),
                ('Branch', models.CharField(choices=[('ICT', 'ICT'), ('ICT with CS', 'ICT with CS'), ('MnC', 'MnC'), ('Robotics', 'Robotics')], default='ICT', max_length=29)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200, null=True)),
                ('Type_of_complaint', models.CharField(choices=[('Cafeteria', 'Cafeteria'), ('Academics', 'Academics'), ('Hostel', 'Hostel'), ('LT & Infrastructure', 'LT & Infrastructure'), ('Sports', 'Sports'), ('Other', 'Other')], max_length=200, null=True)),
                ('Description', models.TextField(max_length=4000, null=True)),
                ('Time', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Solved'), (2, 'InProgress'), (3, 'Pending')], default=3)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
