# Generated by Django 4.2.6 on 2023-11-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_supervisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
